### ISSUE TITLE
Beware: docker tags 0.1.1 and 0.1.2 were overwritten with default behavior changed

### ISSUE THREAD

**Issue by joemiller** [sethvargo/vault-init#10]
We noticed a failure in a weekly acceptance test we run that creates a new instance of Vault, runs some tests, then tears it down. This week's test failed to setup the Vault instance. We tracked the cause down to the 0.1.1 and 0.1.2 tags on Docker Hub having been overwritten with the latest changes. The observed issues that led us here were:

1. The default skip-TLS-verification was changed from enabled to disabled as described in #9. This led to vault-init being unable to communicate with vault.
2. Vault auto-unseal was added and set to default. This meant our Vault instance (which has not switched to native auto-unseal) was not unsealed by vault-init.

We were using vault-init:0.1.1. The docker tags for versions 0.1.1 and 0.1.2 on docker hub were overwritten with a new version that had the above two changes in behavior. https://hub.docker.com/r/sethvargo/vault-init/tags

![image](https://user-images.githubusercontent.com/377603/81875076-4fed2100-9534-11ea-8d72-3086afb87115.png)

Our fix to return the original behavior:
- set `VAULT_SKIP_VERIFY=true`
- set `VAULT_AUTO_UNSEAL=false` (we'll migrate to auto unseal soon)

**Comment by ghost** [comment]
Thanks a ton @joemiller for sharing this. Similar issue came up overnight. Your note saved a bunch of pain.

**Comment by sethvargo** [comment]
Uploaded 0.2.0
