### ISSUE TITLE
It fails with ACCESS_TOKEN_SCOPE_INSUFFICIENT"

### ISSUE THREAD

**Issue by laith-leo** [sethvargo/vault-init#16]
```
k logs -n vault vault-0 vault-auto-init        
2022/06/21 20:47:25 Starting the vault-init service...
2022/06/21 20:47:25 Vault is not initialized.
2022/06/21 20:47:25 Initializing...
2022/06/21 20:47:31 Encrypting unseal keys and the root token...
2022/06/21 20:47:32 googleapi: Error 403: Request had insufficient authentication scopes.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "method": "google.cloud.kms.v1.KeyManagementService.Encrypt",
      "service": "cloudkms.googleapis.com"
    },
    "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
  }
]

More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```

**Comment by sethvargo** [comment]
If you're running on a GCE VM, make sure you granted the service account "cloud-platform" oauth permissions.

**Comment by laith-leo** [comment]
It is through GKE, and the nodes are managed by the nodepool

**Comment by sethvargo** [comment]
When you create the cluster, you provide a service account and set of scopes (or permissions) that make up the default credentials that the underlying nodes (aka VMs) will use to access other Google Cloud Services.

![0_YeiQYtVXtqhTGhTJ](https://user-images.githubusercontent.com/408570/175032036-d54a5ad5-21f5-44ab-ad4e-e4071d181343.png)

You need to pick "Allow full access to all Cloud APIs". You could also use Workload Identity Federation instead.
