### ISSUE TITLE
Vault init with AWS KMS and Consul

### ISSUE THREAD

**Issue by sandeepsharmadevops** [sethvargo/vault-init#5]
Hi @sethvargo ,

Hope you are doing well!!!

I was trying to configure vault backed by consul where both should be hosted on k8s cluster and using AWS KMS to auto unseal. After searching a lot i landed up on your youtube video and [github example](https://github.com/sethvargo/vault-on-gke)(excellent articulation, you made my life easy to understand the whole), using which i was able to run vault in k8s cluster with auto unseal. But initial vault init needs to be done as i implemented vault statefulset without auto vault init. I was going through your GO code base of vault-init where Google storage is used as vault backend along with Google KMS for auto unseal, but since my vault cluster is backed by consul and AWS KMS, hence i was not able use your vault init AS-IS.

I need little help from your side on below:
- how this vault init is happening at backend(simple briefing about the whole workflow)
- does it feasible with consul and if yes please point me with some examples so that i can achieve the auto vault init as well.

thanks in advance,

regards

**Comment by sethvargo** [comment]
Hi @sandeepsharmadevops 

This repo is specific for GCP and is somewhat deprecated. Vault has native functionality for auto-unsealing via a number of cloud providers, including AWS.
