### ISSUE TITLE
Rotating Key Support

### ISSUE THREAD

**Issue by somejavadev** [sethvargo/vault-init#6]
Hi,

I would like to know, would the vault-init container support rotating keys as described here: https://cloud.google.com/kms/docs/rotating-keys or should any special care be taken when enabling key rotation?

**Comment by sethvargo** [comment]
Hi @somejavadev - you can rotate the keys, but AFAIK, Vault only encrypts the initial keys once. You'll create new KMS key versions, but only the first one will actually be used to decrypt the data.

You would need to do the following:

1. [Rotate the Cloud KMS key](https://cloud.google.com/kms/docs/key-rotation) (creating a new key version)
2. [Rekey Vault](https://www.vaultproject.io/docs/commands/operator/rekey/)

Enabling a Cloud KMS rotation schedule won't improve your security posture without also regularly re-keying Vault.
